### ISSUE TITLE
I2C: Mixed transfers methods causing Interrupts to hang MCU

### ISSUE THREAD

**Issue by flatirondesigns** [STMicroelectronics/stm32l4xx_hal_driver#13]
STM32CubeIDE v 1.14.0
NUCLEO-L412KB

This issue appears to be the same as
https://github.com/STMicroelectronics/STM32CubeH7/issues/260#top

If I do a DMA transfer over I2C then followed by HAL_I2C_Mem_Write, it hangs.  The TXIE is still set after the DMA transfer. If I manually clear it through the IDE before executing the Mem_Write, it does not hang.

**Comment by RJMSTM** [comment]
Hello @flatirondesigns,

Thank you for this report, actually this issue has already been detected and fixed. The fix is already available in the frame of the v1.18.0 release published a couple of weeks ago. The linking error should disappear once you will upgrade to this version.

Thank you again for your contribution.
With regards,

**Comment by flatirondesigns** [comment]
Oh, sorry. I didn't see a new version. I will check again. Thank you.

**Comment by flatirondesigns** [comment]
Sorry, I didn't realize there was a separate menu option to download the latest FW. It does fix my issue. Thanks again.
